### ISSUE TITLE
Registration: Not all error messages are translated

### ISSUE THREAD

**Issue by DirkFedermann** [simracingtools/racecontrol-server#7]
**Describe the bug**
The 3 last error messages in the registration are not all translated.

**To Reproduce**
1. Go to the registration page
2. Select a language. For example 'Deutsch'
3. Click on 'Registrieren' ('Register')

**Expected behavior**
All error messages should be in the language you've selected.

**Screenshots**
![riSQ6IC5Ox](https://user-images.githubusercontent.com/8479769/200173726-8ad7f998-68ee-4aab-a28b-4984e66e87b1.jpg)

**Comment by robbyb67** [comment]
Number of languages is reduced to German and English.
Appropriate German error messages are added to Keycloak configuration.
